### ISSUE TITLE
Refresh existing pages using ENABLE_GATSBY_REFRESH_ENDPOINT

### ISSUE THREAD

**Issue by zackphilipps** [thinhle-agilityio/gatsby-source-apiserver#26]
👋 Hello @thinhle-agilityio! Thanks for your work on this plugin; it's working really well for us.

I'm using `ENABLE_GATSBY_REFRESH_ENDPOINT` with `gatsby develop` locally and have had success when nodes are added. However, when changing one of the fields on the node, or deleting a node, it doesn't look like the source data is successfully refreshed. In addition, when adding a node after either one of those changes, the preceding changes are not refreshed.

See https://github.com/gatsbyjs/gatsby/issues/14653 for more details.

@freiksenet thinks it's because this plugin is generating new IDs with each fetch. Do you think there's a way to make `ENABLE_GATSBY_REFRESH_ENDPOINT` work as advertised? I'm happy to work on a PR if you can get me pointed in the right direction.

P.S. My use case is this: I would like to have a staging site set up on a Heroku server or something similar that is constantly running `gatsby develop` and resourcing data when it changes. Just for previewing purposes while we have a team editing content.

**Comment by thinhle-agilityio** [comment]
@zackphilipps Your requested feature only work with development environment since you use `gatsby develop`. Production environment cannot support this feature because it is a static build.

So, if you want to make a MR into this plugin, please make sure you specify `NODE_ENV === 'development'` in your MR code. I don't want it break other build since id might be used to cache static assets.
Thanks

**Comment by zackphilipps** [comment]
Thanks for merging @thinhle-agilityio !
